#!/bin/bash
# Quick Firebase Setup Script for Brain Grain

echo "🔥 Firebase + GitHub Pages Setup for Brain Grain"
echo "================================================"
echo ""
echo "STEP 1: Create Firebase Project"
echo "--------------------------------"
echo "1. Open: https://console.firebase.google.com/"
echo "2. Click 'Add project'"
echo "3. Name: brain-grain (or your choice)"
echo "4. Disable Google Analytics"
echo "5. Click 'Create project'"
echo ""
echo "Press Enter when project is created..."
read

echo ""
echo "STEP 2: Get Firebase Config"
echo "----------------------------"
echo "1. Click gear icon ⚙️ → 'Project settings'"
echo "2. Scroll to 'Your apps'"
echo "3. Click Web icon </>"
echo "4. App nickname: Brain Grain Web"
echo "5. DON'T check Firebase Hosting"
echo "6. Click 'Register app'"
echo "7. COPY the firebaseConfig object"
echo ""
echo "Press Enter when you've copied the config..."
read

echo ""
echo "STEP 3: Enable Realtime Database"
echo "--------------------------------"
echo "1. Left sidebar → 'Realtime Database'"
echo "2. Click 'Create Database'"
echo "3. Select your region"
echo "4. Start in TEST MODE"
echo "5. Click 'Enable'"
echo ""
echo "Press Enter when database is enabled..."
read

echo ""
echo "STEP 4: Update firebase-config.js"
echo "----------------------------------"
echo "Now edit firebase-config.js and paste your config"
echo ""
echo "Replace this:"
echo "  apiKey: 'YOUR_API_KEY_HERE',"
echo ""
echo "With your actual values from Firebase console"
echo ""
read -p "Press Enter when you've updated firebase-config.js..."

echo ""
echo "STEP 5: Test Cloud Sync"
echo "------------------------"
echo "1. Refresh your browser (Ctrl+F5)"
echo "2. Login to admin panel"
echo "3. You should see '☁️ Sync to Cloud' button (green)"
echo "4. Click it to test"
echo ""
read -p "Press Enter when cloud sync works..."

echo ""
echo "STEP 6: Enable Auto-Sync"
echo "------------------------"
echo "1. Click '⚙️ Cloud Settings'"
echo "2. Enable 'Automatic Cloud Sync'"
echo "3. Done! Data now syncs automatically"
echo ""
read -p "Press Enter to continue to GitHub Pages setup..."

echo ""
echo "STEP 7: Deploy to GitHub Pages"
echo "-------------------------------"
echo "Run these commands:"
echo ""
echo "  git add ."
echo "  git commit -m 'Add cloud storage with Firebase'"
echo "  git push origin main"
echo ""
echo "Then:"
echo "1. Go to your GitHub repo"
echo "2. Settings → Pages"
echo "3. Source: Deploy from branch"
echo "4. Branch: main, folder: / (root)"
echo "5. Click Save"
echo ""
echo "Your app will be live at:"
echo "https://YOUR_USERNAME.github.io/REPO_NAME/"
echo ""
echo "✅ Setup Complete!"
echo "=================="
echo ""
echo "Your data is now:"
echo "  ✅ Stored in Firebase Cloud"
echo "  ✅ Accessible from anywhere"
echo "  ✅ Automatically synced"
echo "  ✅ Deployed on GitHub Pages"
echo ""
echo "For production, update Firebase Database rules:"
echo "https://console.firebase.google.com/ → Realtime Database → Rules"
